# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow builds, tests, and creates a Docker image
# for an ASP.NET Core application built on .NET 8.
#
# To learn more about ASP.NET Core and .NET,
# refer to https://dotnet.microsoft.com/en-us/apps/aspnet
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Docker
# Make sure your Dockerfile exists in the root directory of the repository.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Actions,
# refer to https://docs.github.com/en/actions

name: PrimaryVets CI/CD

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  build:

    strategy:
      matrix:
        configuration:
          - Release

    runs-on: windows-latest

    env:
      Solution_Name: PrimaryVets.sln
      Configuration: ${{ matrix.configuration }}

    steps:

    # Checkout the source code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore NuGet packages
    - name: Restore the application
      run: dotnet restore $env:Solution_Name

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --configuration $env:Configuration --no-restore

    # Build the application
    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore

    # Build Docker image
    - name: Build Docker image
      run: docker build -t primaryvets:latest .

    # Display Docker images
    - name: Display Docker images
      run: docker images
